update_fastlane

default_platform(:android)

platform :android do

  
  desc "Runs all the tests"
  lane :test do
    gradle(
      task: "build",
      project_dir: "/root/e-com-react-native/android"
    )
  end

end
